name = "NonsmoothOptim"
uuid = "0dfc7a1c-e419-4470-a3bc-787e626244db"
authors = ["Thibaut Cuvelier <cuvelier.thibaut@gmail.com> and contributors"]
version = "0.1.0"

[deps]
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
julia = "1"
JuMP = "^0.21, ^0.22"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
